language: node_js

node_js:
- "stable"
cache: 
  dependencies: 
    node_modules

script: 
  - npm install
  - npm test
  - npm run build

deploy:
  provider: surge
  skip_cleanup: true
  domain: react-test-tdd.surge.sh
  project: ./build/

on:
  branch: main

